development:
  adapter: postgresql
  encoding: unicode
  database: taskmaster_development
  pool: 5
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: postgres
  password: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 